### ISSUE TITLE
Register Reader fails to find file automatically

### ISSUE THREAD

**Issue by rcpeene** [harp-tech/harp-python#45]
I'm running the following code 
```python
harp_path = Path(r"directory\myPathTo.harp")
reader = harp.create_reader(harp_path)
print([r for r in reader.registers.keys()])
print(reader.AnalogData.read())
```
and it yields the error; 
```python
Traceback (most recent call last):
  File "C:\Users\carter.peene\Desktop\Projects\openscope_upload\process_slap2.py", line 63, in <module>
    print(reader.AnalogData.read())
TypeError: _compose_parser.<locals>.parser() missing 1 required positional argument: 'data'
```

When the files in my directory look as follows;
```
> device.yml
> Behavior_0.bin
> Behavior_1.bin
.
.
.
> Behavior_121.bin
> Behavior_122.bin
```

**Comment by bruno-f-cruz** [comment]
This seems to be a regression introduced in `0.4.0` by the `_compose_parser` delegate. (All registers that build the parser raise this error). The error is not reproducible in `0.3.0`

```python 
from harp import create_reader

reader = create_reader("<path>/Behavior.harp")
for name, reg in reader .registers.items():
    try:
        reg.read()
    except Exception as e:
        print(f"Error reading register {name}: {e}")
```

**Comment by bruno-f-cruz** [comment]
The error seems to be in the building of the `payloadspec`.
The unit tests are not catch the edge case because the device.yml is using a naive array parser and not instantiating from a fully defined payload-spec (e.g.:)

```yml
  AnalogData:
    address: 44
    type: S16
    length: 3
    access: Event
    description: Voltage at the ADC input and encoder value on Port 2
    payloadSpec:
      AnalogInput0:
        offset: 0
        description: The voltage at the output of the ADC channel 0.
      Encoder:
        offset: 1
        description: The quadrature counter value on Port 2
      AnalogInput1:
        offset: 2
        description: The voltage at the output of the ADC channel 1.
```
